language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  #Tagging
  - docker tag udagram-reverseproxy tuanit2304/udagram-reverseproxy
  - docker tag udagram-api-feed tuanit2304/udagram-api-feed
  - docker tag udagram-api-user tuanit2304/udagram-api-user
  - docker tag udagram-frontend tuanit2304/udagram-frontend:local

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tuanit2304/udagram-reverseproxy
  - docker push tuanit2304/udagram-api-feed
  - docker push tuanit2304/udagram-api-user
  - docker push tuanit2304/udagram-frontend:local